Login front-end
Los-senior-leads/ProyectoLSL pull request #1
Opened 2021-11-29 02:04 UTC by AleChirinos

Se realizo el login de front-end.
Tareas que faltan: 
- Conectar usuarios con la base de datos para permitir el acceso.
- Conexión con Back-end para realizar HTTP response, para los distintos usuarios con distintos permisos

2021-11-30 02:13 UTC, AndreM22 approved these changes
Interfaz amigable sencilla y acorde a los mock ups para la pantalla de login

2021-11-30 03:49 UTC, darkv314 commented on src/app/login/login/login.component.css
> +html, body{
Es necesario modificar el archivo css?
Tengo entendido que al usar bootstrap se les añade clases a los componentes de html para que se hagan los cambios de css.

2021-11-30 04:11 UTC, darkv314 commented on src/app/login/login/login.component.html
> +  <div class = "border">
Hay un rectangulo que esta al principio del del formulario, creo que deberiamos quitarlo

2021-11-30 04:12 UTC, darkv314 requested changes
Solucionar los aspectos relacionados a css y responsiveness

2021-11-30 04:12 UTC, darkv314 commented on src/app/login/login/login.component.css
> +html, body{
El contenido no es full responsive, deberiamos solucionar eso

2021-11-30 04:33 UTC, AleChirinos commented on src/app/login/login/login.component.html
> +  <div class = "border">
Ese rectángulo esta por fuera del formulario para poder estilizarlo, sin el mismo el formulario crecería a lo ancho de la pantalla  y como se utiliza ng-bootstrap es más complicado cambiar el diseño css de un elemento ya definido.

2021-11-30 04:35 UTC, AleChirinos commented on src/app/login/login/login.component.css
> +html, body{
No existe un requerimiento de que el sistema deba ser responsivo. Considero que deberíamos enfocarnos primero en la parte funcional y en los requerimientos. Después podríamos cambiar a que toda la aplicación sea responsiva

2021-12-03 10:01 UTC, darkv314 approved these changes

2021-12-03 11:49 UTC, merged